runtime: php55
api_version: 1

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|ico))$
  static_files: \1
  upload: .+\.(gif|png|jpg|ico)$
  application_readable: true

- url: /css
  static_dir: css

# # Serve php scripts.
# - url: /(.+\.php)$
#   script: \1

- url: /(.+)
  script: \1

- url: /.*
  script: index.php